name: testRCRelease

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      issue_url:
        description: |
          issue_url: the GitHub issue URL that tracks the status of Providers release
          (Either rc_testing_branch or issue_url is required, and you cannot give both.)
        required: false
      base_git_rev:
        description: 'The base git revision to test Providers RCs (temp)'
        required: false
        type: string
        default: 'main'
  pull_request:
defaults:
  run:
    working-directory: python-sdk
jobs:
  validate-manual-input:
    runs-on: 'ubuntu-20.04'
    steps:
      - name: Validate user input
        if: |
           inputs.issue_url == ''
        run: |
          echo "issue_url is required"
          exit 1

  create-branch-for-testing-rc-release:
    needs: validate-manual-input
    runs-on: 'ubuntu-20.04'
    if: ${{ inputs.issue_url }}
    steps:

      - name: Checkout pull/${{ github.event.number }}
          uses: actions/checkout@v3
          with:
            ref: ${{ github.event.pull_request.head.sha }}

      - name: Update project dependencies to use RC providers
        run: |
          echo "Updating pyproject.toml with RC provider packages"
          pwd
          echo "Updating pyproject.toml with RC provider packages"
          ls dev/
          echo "Updating pyproject.toml with RC provider packages"
          cat dev/replace_dependencies.py
          python ../.github/scripts/replace_dependencies.py --issue-url ${{ inputs.issue_url }}
          git diff

    outputs:
      rc_testing_branch: ${{ steps.create_rc_branch.outputs.rc_testing_branch }}
